### PR TITLE
Add services examples: AddTwoInts server

### PR DESCRIPTION
**Pull request by jamoralp**
Signed-off-by: Jose Antonio Moral <joseantoniomoralparras@gmail.com>

### CODE REVIEW

**Comment by richiprosima** [comment]
Buildstatus:[BuildStatus](http://jenkins.eprosima.com:8080/job/integration_service_docs_manual/40/)

**Comment by richiprosima** [comment]
Buildstatus:[BuildStatus](http://jenkins.eprosima.com:8080/job/integration_service_docs_manual/41/)

**Comment by richiprosima** [comment]
Buildstatus:[BuildStatus](http://jenkins.eprosima.com:8080/job/integration_service_docs_manual/42/)

**Comment by richiprosima** [comment]
Buildstatus:[BuildStatus](http://jenkins.eprosima.com:8080/job/integration_service_docs_manual/46/)

**Comment by richiprosima** [comment]
Buildstatus:[BuildStatus](http://jenkins.eprosima.com:8080/job/integration_service_docs_manual/47/)

**Review by laura-eprosima — CHANGES_REQUESTED** [review]

**Review by laura-eprosima — APPROVED** [review]

**Pull request merged**
